[tool.poetry]
package-mode = false
name = "documentation-python"
description = "Documentation and exercises of the Python programming language and some its libraries and frameworks."
authors = ["dyegop <poncelas.professional@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
requests = "^2.32.0"
pandas = "^2.2.2"
pillow = "^10.3.0"
openpyxl = "^3.1.2"
bs4 = "^0.0.2"
flask = "^3.0.3"
flask-restful = "^0.3.10"
flask-jwt = "^0.3.2"
openai = "^1.27.0"
python-dotenv = "^1.0.1"

[tool.poetry.group.dev.dependencies]
mypy = "^1.10.0"
black = "^24.4.2"
pre-commit = "^3.7.1"
pylint = "^3.1.0"

[build-system]
requires = "poetry-core"
build-backend = "poetry.core.masonry.api"
