[tool.poetry]
package-mode = false
name = "python-documentation"
description = "Documentation and exercises of the Python programming language and some its libraries and frameworks."
authors = ["dyegop <poncelas.professional@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
